apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chay-techs-development
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chay-techs-development
  source:
    repoURL: 'https://github.com/ChayFadida/PortfolioGitOps.git'
    path: 'environments/develop'
    targetRevision: 'develop'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chay-techs-production
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chay-techs-production
  source:
    repoURL: 'https://github.com/ChayFadida/PortfolioGitOps.git'
    path: 'environments/master'
    targetRevision: 'master'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true